"""
print(chr(0x250F), end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(chr(0x2513))

print(chr(0x2503), end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(chr(0x2503))

print(chr(0x2503), end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(chr(0x2503))

print(chr(0x2503), end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(chr(0x2503))

print(chr(0x2517), end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(' ', end='')
print(chr(0x251B))

"""
from matrix import Matrix


m4 = Matrix.from_string('1 2 3; 4 5 6; 7 8 9')
print(m4._minor_matrix(2, 2))